namespace TotvsConsincoMock.MockData;

public static class TributacaoProdutosMock
{
    public static List<object> Get() =>
    [
        new
        {
            NumeroEmpresa = 1,
            UFEmpresa = "SP",
            UFDestino = "SP",
            RegimeTributacao = "NORMAL",
            NumeroDivisao = 1,
            NumeroTributacao = 200,
            TipoTributacao = "SN",
            CstIcms = "000",
            PercentualICMS = 100.0m,
            PercentualIsentoICMS = 0.0m,
            AliquotaICMS = 18.0m,
            AliquotaPIS = 1.65m,
            AliquotaCofins = 7.60m,
            MVA = 0.0m,
            AliquotaICMSST = 0.0m,
            ReducaoBaseICMSST = 0,
            ValorPautaICMSST = 0.0m,
            AliquotaIPI = 0.0m,
            AliquotaIPISaida = 0.0m,
            ValorPautaIPI = 0.0m,
            AliquotaFCPICMS = 0.0m,
            UsaPMCBaseST = "N",
            STConformeEntrada = "N",
            SomaIPInoST = "N",
            CodigoAcessoPrincipal = "06632956",
            IdProduto = 2001,
            IdFamilia = 100,
            IdProdutoBase = 2001,
            DataUltimaAtualizacao = "2026-06-20T09:00:00Z"
        },
        new
        {
            NumeroEmpresa = 1,
            UFEmpresa = "SP",
            UFDestino = "SP",
            RegimeTributacao = "NORMAL",
            NumeroDivisao = 1,
            NumeroTributacao = 201,
            TipoTributacao = "SN",
            CstIcms = "060",
            PercentualICMS = 0.0m,
            PercentualIsentoICMS = 0.0m,
            AliquotaICMS = 0.0m,
            AliquotaPIS = 1.65m,
            AliquotaCofins = 7.60m,
            MVA = 35.0m,
            AliquotaICMSST = 18.0m,
            ReducaoBaseICMSST = 0,
            ValorPautaICMSST = 0.0m,
            AliquotaIPI = 0.0m,
            AliquotaIPISaida = 0.0m,
            ValorPautaIPI = 0.0m,
            AliquotaFCPICMS = 0.0m,
            UsaPMCBaseST = "N",
            STConformeEntrada = "N",
            SomaIPInoST = "N",
            CodigoAcessoPrincipal = "4005808555345",
            IdProduto = 2002,
            IdFamilia = 110,
            IdProdutoBase = 2002,
            DataUltimaAtualizacao = "2026-06-20T09:10:00Z"
        },
        new
        {
            NumeroEmpresa = 1,
            UFEmpresa = "SP",
            UFDestino = "SP",
            RegimeTributacao = "NORMAL",
            NumeroDivisao = 1,
            NumeroTributacao = 202,
            TipoTributacao = "SN",
            CstIcms = "000",
            PercentualICMS = 100.0m,
            PercentualIsentoICMS = 0.0m,
            AliquotaICMS = 18.0m,
            AliquotaPIS = 1.65m,
            AliquotaCofins = 7.60m,
            MVA = 0.0m,
            AliquotaICMSST = 0.0m,
            ReducaoBaseICMSST = 0,
            ValorPautaICMSST = 0.0m,
            AliquotaIPI = 5.0m,
            AliquotaIPISaida = 5.0m,
            ValorPautaIPI = 0.0m,
            AliquotaFCPICMS = 2.0m,
            UsaPMCBaseST = "N",
            STConformeEntrada = "N",
            SomaIPInoST = "N",
            CodigoAcessoPrincipal = "6452024011229",
            IdProduto = 2003,
            IdFamilia = 120,
            IdProdutoBase = 2003,
            DataUltimaAtualizacao = "2026-06-20T09:20:00Z"
        }
    ];
}

